name: combine-multi-arch-images
description: ""

inputs:
  package-name:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Set image name
      id: set-image-name
      run: echo "image-name=ghcr.io/${{ github.repository_owner }}/${{ inputs.package-name }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get all tags
      id: get-all-tags
      run: |
        base_url="https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ inputs.package-name }}/versions"
        echo "base_url: $base_url"

        all_tags=()
        for page in $(seq 1 10); do
          page_url="${base_url}?page=$page"
          echo -e "\npage_url: $page_url"

          page_tags=$(curl -fsSL "$page_url" -H "Authorization: token ${{ github.token }}" | jq ".[].metadata.container.tags[]" | cut -d '"' -f 2)
          echo -e "\n[page_tags]\n$page_tags"

          if [ "$page_tags" = "" ]; then
            echo "No tags found in the page $page."
            break
          fi

          for tag in $(IFS=$'\n'; echo "$page_tags"); do
            all_tags+=("$tag")
          done
        done

        all_tags=$(printf "%s\n" ${all_tags[@]})
        echo -e "\n[all_tags]\n$all_tags"

        echo "tags=$(printf "%s " $all_tags | sed 's/\s*$//')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get base tags
      id: get-base-tags
      run: |
        echo "All tags: ${{ steps.get-all-tags.outputs.tags }}"
        amd64_tags=()
        arm64_tags=()
        for tag in ${{ steps.get-all-tags.outputs.tags }}; do
          echo "Processing tag: $tag"
          if [[ $tag == *-amd64 ]]; then
            amd64_tags+=("${tag%-amd64}")
            echo "Added to amd64_tags: ${tag%-amd64}"
          elif [[ $tag == *-arm64 ]]; then
            arm64_tags+=("${tag%-arm64}")
            echo "Added to arm64_tags: ${tag%-arm64}"
          else
            echo "Tag doesn't match expected pattern: $tag"
          fi
        done
        base_tags=($(printf "%s\n" "${amd64_tags[@]}" "${arm64_tags[@]}" | sort -u))

        echo -e "\n[amd64_tags]\n${amd64_tags[*]}"
        echo -e "\n[arm64_tags]\n${arm64_tags[*]}"
        echo -e "\n[base_tags]\n${base_tags[*]}"

        echo "tags=${base_tags[*]}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Docker manifest
      run: |
        IFS=' ' read -ra BASE_TAGS <<< "${{ steps.get-base-tags.outputs.tags }}"
        echo "Base tags: ${BASE_TAGS[*]}"
        for base_tag in "${BASE_TAGS[@]}"; do
          echo -e "\nProcessing base_tag: $base_tag"

          amd64_tag=$(echo "${{ steps.get-all-tags.outputs.tags }}" | tr ' ' '\n' | grep "^${base_tag}-amd64$" || true)
          arm64_tag=$(echo "${{ steps.get-all-tags.outputs.tags }}" | tr ' ' '\n' | grep "^${base_tag}-arm64$" || true)

          echo "amd64_tag: $amd64_tag"
          echo "arm64_tag: $arm64_tag"

          manifest_args=()
          if [ -n "$amd64_tag" ]; then
            manifest_args+=("${{ steps.set-image-name.outputs.image-name }}:$amd64_tag")
            echo "Added to manifest_args: ${{ steps.set-image-name.outputs.image-name }}:$amd64_tag"
          else
            echo "No amd64 tag found for '$base_tag'."
          fi

          if [ -n "$arm64_tag" ]; then
            manifest_args+=("${{ steps.set-image-name.outputs.image-name }}:$arm64_tag")
            echo "Added to manifest_args: ${{ steps.set-image-name.outputs.image-name }}:$arm64_tag"
          else
            echo "No arm64 tag found for '$base_tag'."
          fi

          if [ ${#manifest_args[@]} -gt 0 ]; then
            echo "Creating manifest for $base_tag with ${#manifest_args[@]} architectures"
            echo "Manifest command: docker manifest create ${{ steps.set-image-name.outputs.image-name }}:$base_tag ${manifest_args[*]}"
            if docker manifest create "${{ steps.set-image-name.outputs.image-name }}:$base_tag" "${manifest_args[@]}"; then
              echo "Pushing manifest: docker manifest push ${{ steps.set-image-name.outputs.image-name }}:$base_tag"
              if docker manifest push "${{ steps.set-image-name.outputs.image-name }}:$base_tag"; then
                echo "Successfully pushed manifest for $base_tag"
              else
                echo "Failed to push manifest for $base_tag"
                docker manifest inspect "${{ steps.set-image-name.outputs.image-name }}:$base_tag"
              fi
            else
              echo "Failed to create manifest for $base_tag"
              echo "Docker info:"
              docker info
              echo "Docker version:"
              docker version
            fi
          else
            echo "No valid tags found for '$base_tag'. Skipping manifest creation."
          fi
        done
      shell: bash
